### PR TITLE
feat: create home screen

### PR DESCRIPTION
**Pull request by FilipiRafael**
# [GOAL](issue)

### ✨ Description:
Home Screen

### 🛠 Changes

- [X] : update babel-config path alias from src to app
- [x] : quote animation
- [x] : add daily quote mocks for each language
- [x] : add copy to i18n dictionary
- [x] : store the date of the last quote update to manage daily updates (MMKV)
- [x] : implement a function to check the current date and update the quote if necessary (MMKV)
- [x] : save quote button
- [x] : social share button

### 🧪 How Has This Been Tested?

- [x] Tested on IOS
- [x] Tested on Android

### 📸 How it's looking
Screenshot 2024-08-09 at 17 34 46

### CODE REVIEW

**Comment by gustavoabel** [comment]
@FilipiRafael you finished of created the screens on figma?

**Comment by FilipiRafael** [comment]
> @FilipiRafael you finished of created the screens on figma?

Look at the next task on the check-list, I'm doing it right now

**Comment by gustavoabel** [comment]
@FilipiRafael we will focus on finishing all screens before opening any PR, and we will also avoid involving tasks that are not related to code (figma screens) in PR's.

**Review by gustavoabel — APPROVED** [review]
LGTM

**Pull request merged**
